### ISSUE TITLE
Enhancement: Add ChargeCooldown Support

### ISSUE THREAD

**Issue by StormFX** [SFX-WoW/Masque#1]
A new feature was added that gives charged abilities their own cooldown. Masque should catch-and-resize those that use the native API and provide a method for those that don't.

**Comment by out1aw** [comment]
Was added or will be added? Your last update was 07-20-15

**Comment by StormFX** [comment]
Will be added.

**Comment by out1aw** [comment]
Any ETA? Wainting for more than 3 months

**Comment by StormFX** [comment]
All I can say is "soon". I have about half of it dry-coded, but I don't actually play anymore and don't even have the game installed at the moment, so once I get the code finished, the game reinstalled and get it tested, then it'll be ready. But real life trumps, so. /shrug

**Comment by StormFX** [comment]
Should be "testable". It seems to work with Dominos, but Bartender uses its own library API so he'll have to update his add-on before it works there.

**Comment by out1aw** [comment]
So, can you coop with Bartender Dev to fix this? H8 this bug so much.

**Comment by StormFX** [comment]
I'll fix what's relevant to Masque. Nevcairel will have to update his add-on.
