### ISSUE TITLE
ItemRack Support?Request: [Title]

### ISSUE THREAD

**Issue by Baracoot** [SFX-WoW/Masque#120]
**Game Version**
_Which version of the game are you using? Eg: `Retail - 8.3.7`_

1.13.5

**Add-On Version**
_Which version of the add-on are you using? Eg: `8.3.0-Classic`_

1.9.0 

**Is the improvement related to a problem?**
_Provide a clear and concise description of the problem._

No.

**Describe the Improvement**
_Provide a clear and concise description of the improvement._

[Improvement]

**Code**
_If applicable, provide any relevant code related to the improvement._

```text
[Code]
```

**Screenshots**
_If applicable, add screenshots to help demonstrate the problem or improvement._

[Screenshots]

**Additional Information**
_Provide any additional information that may be relevant._

[Information]

**Comment by StormFX** [comment]
Masque is a library.  ItemRack would have to add support for Masque, not the other way around.
