### ISSUE TITLE
Error with Bartender

### ISSUE THREAD

**Issue by OldWorldRaiders** [SFX-WoW/Masque#129]
**Game Version**
Retail

[Game Version]

**Add-On Version**
The 9.0.5 retail release, newest

[Add-On Version]

**Describe the Issue**
I get this error message:

Message: ...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "UNIT_POWER"
Time: Thu Apr 15 14:47:35 2021
Count: 1
Stack: ...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "UNIT_POWER"
[string "=(tail call)"]: ?
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface\AddOns\PitBull4_HolyPowerBar\HolyPowerBar.lua"]:39: in function <...erface\AddOns\PitBull4_HolyPowerBar\HolyPowerBar.lua:38>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1435: in function `LoadModules'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1575: in function `OnProfileChanged'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1645: in function <Interface\AddOns\PitBull4\Main.lua:1615>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

[Description]

**Steps To Reproduce**
I logged in and got the message.

**Error Message**
Message: ...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "UNIT_POWER"
Time: Thu Apr 15 14:47:35 2021
Count: 1
Stack: ...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "UNIT_POWER"
[string "=(tail call)"]: ?
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface\AddOns\PitBull4_HolyPowerBar\HolyPowerBar.lua"]:39: in function <...erface\AddOns\PitBull4_HolyPowerBar\HolyPowerBar.lua:38>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1435: in function `LoadModules'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1575: in function `OnProfileChanged'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1645: in function <Interface\AddOns\PitBull4\Main.lua:1615>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by StormFX** [comment]
This is a cascaded error and unrelated to Masque. Neither Masque nor Bartender access "UNIT_POWER", therefore it's likely an issue with PitBull.

**Comment by OldWorldRaiders** [comment]
Thank you! Apologies for posting here.
