### ISSUE TITLE
Retail Error

### ISSUE THREAD

**Issue by OldWorldRaiders** [SFX-WoW/Masque#131]
Hey All,

I am getting this error and I am not sure why. I get it when logging in while in a party.

7x Bartender4\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PLAYER_PET_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Bartender4\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@ClassTimer\ClassTimer-2.4.90001.1.lua"]:342: in function <ClassTimer\ClassTimer.lua:338>
[string "=[C]"]: ?
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by StormFX** [comment]
This isn't related to Masque. [ClassTimers](https://www.wowace.com/projects/classtimer/issues/113) is outdated](https://www.wowace.com/projects/classtimer/issues/113).
