### ISSUE TITLE
Bug: [9.1 Freeze when changing talents]

### ISSUE THREAD

**Issue by JH0Ni-github** [SFX-WoW/Masque#140]
**Game Version**
9.1

**Add-On Version**
Latest release

**Describe the Issue**
I'm getting 10sec freeze when changing talents in arena or open world with war mode on. Issue won't show when masque is not loaded.

[Description]
1x ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:30: script ran too long
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:30: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:291: in function `NotifyChange'
[string "@Masque\Libs\LibDualSpec-1.0\LibDualSpec-1.0-20.lua"]:443: in function <...dOns\Masque\Libs\LibDualSpec-1.0\LibDualSpec-1.0.lua:412>

Locals:
handlers = <table> {
  = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
  = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
  = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
  = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
  = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
  = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
}
index = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:85
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 OnEnable = <function> defined @TidyPlates_ThreatPlates\Core.lua:387
 UnregisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:111
 baseName = "TidyPlates_ThreatPlates"
 OnInitialize = <function> defined @TidyPlates_ThreatPlates\Core.lua:333
 ConfigTableChanged = <function> defined @TidyPlates_ThreatPlates\Options.lua:9559
 Printf = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:69
 ProfChange = <function> defined @TidyPlates_ThreatPlates\Options.lua:9504
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 ChatCommandDebug = <function> defined @TidyPlates_ThreatPlates\Commands.lua:160
 ChatCommand = <function> defined @TidyPlates_ThreatPlates\Commands.lua:114
 CheckForFirstStartUp = <function> defined @TidyPlates_ThreatPlates\Core.lua:203
 name = "TidyPlatesThreat"
 PLAYER_REGEN_DISABLED = <function> defined @TidyPlates_ThreatPlates\Core.lua:564
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 PLAYER_REGEN_ENABLED = <function> defined @TidyPlates_ThreatPlates\Core.lua:536
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 ToggleNameplateModeEnemyUnits = <function> defined @TidyPlates_ThreatPlates\Core.lua:470
 PLAYER_LOGIN = <function> defined @TidyPlates_ThreatPlates\Core.lua:524
 PLAYER_ENTERING_WORLD = <function> defined @TidyPlates_ThreatPlates\Core.lua:489
 MediaUpdate = <function> defined @TidyPlates_ThreatPlates\Core.lua:427
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:54
 SetRole = <function> defined @TidyPlates_ThreatPlates\Database.lua:83
 ToggleNameplateModeNeutralUnits = <function> defined @TidyPlates_ThreatPlates\Core.lua:461
 ReloadTheme = <function> defined @TidyPlates_ThreatPlates\Core.lua:163
 OnDisable = <function> defined @TidyPlates_ThreatPlates\Core.lua:408
 IsModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 OpenOptions = <function> defined @TidyPlates_ThreatPlates\Options.lua:9564
 CheckForIncompatibleAddons = <function> defined @TidyPlates_Threa

**Comment by StormFX** [comment]
Disable everything except Masque and the add-on that it's skinning and try it.

**Comment by JH0Ni-github** [comment]
Seems hard to reproduce the error without entering arena it seems. [GladiusEx](https://www.curseforge.com/wow/addons/gladiusex) is the only masque skinned addon that I'm using when I encounter these freezes when talent switching and this has been happening since season 2 start with multiple characters. With my other skinned addons (Bartender,ElvUI,OPie,WeakAuras) I haven't had any issues.

**Comment by StormFX** [comment]
Is that with _only_ GladiusEx and Masque enabled? Note that with the way library loading and error attribution works, it's hard to tell what's actually causing the issue with manually testing each add-on that uses a given library. It does seem that LibDualSpec is the library but it's hard to tell what add-on is actually causing it. Masque's inclusion in the error string doesn't mean that it's caused by Masque, but rather that Masque's instance of LibDualSpec was the last one to be loaded. Therefore, it's important to testing various combinations to narrow things down. You'll need to see which add-ons support LibDualSpec and test each one individually.

**Comment by JH0Ni-github** [comment]
I googled for a similar issue and commented out Masque's LibDualSpec-1.0.lua lines 422-423 and I haven't seen the error since, even in arenas where it was most common.

**Comment by StormFX** [comment]
Hm. At that point, you could disable LibDualSpec-1.0 altogether.

**Comment by StormFX** [comment]
I'm assuming you got your solution from Bartender4's issues page?  It indicates to me that there's an issue with LibDualSpec, rather than Masque.

**Comment by JH0Ni-github** [comment]
Yeah iirc it was Bartender4 issue as well. Well no problem with Masque then, other than getting a working lib i guess.
