### ISSUE TITLE
Bug: Action Blocked Error

### ISSUE THREAD

**Issue by antedap** [SFX-WoW/Masque#151]
**Game Version**
_Which version of the game are you experiencing this issue on? Eg: `Retail - 8.3.7`_

Retail - 9.1.5.41031

**Add-On Version**
_Which version of the add-on are you experiencing this issue on? Eg: `8.3.0-Classic`_

Masque 9.1.1

**Describe the Issue**
I think the problem is a conflict with world quest tracker and Masque, when I try to list a group for world quest the addon should compile automatically the title of the group, but Masque is blocking it 

[Description]

**Steps To Reproduce**
_Provide steps to reproduce the issue:_

1. Using World Quest Tracker
2. Click on the Find group button
3. Start group in the dungeon finder

**Error Message**
Interface Action failed because of an Addon

```text
2x [ADDON_ACTION_BLOCKED] AddOn 'Masque' tried to call the protected function 'CreateListing()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `CreateListing'
[string "@FrameXML\LFGList.lua"]:1025: in function `LFGListEntryCreation_ListGroupInternal'
[string "@FrameXML\LFGList.lua"]:1085: in function `LFGListEntryCreation_CheckAutoCreate'
[string "@FrameXML\LFGList.lua"]:656: in function `LFGListEntryCreation_Show'
[string "@FrameXML\LFGList.lua"]:2057: in function <FrameXML\LFGList.lua:2054>
[string "=[C]"]: ?
[string "=[C]"]: ?
```

**Screenshots**
http://prntscr.com/200u9uc

[Screenshots]

**Additional Information**
_Provide any additional information that may be relevant to this issue._

[Information]

**Comment by StormFX** [comment]
This is an error propagated to Masque by something else. Masque doesn't call that function.

**Comment by antedap** [comment]
oh, thank you for the fast reply!
