### ISSUE TITLE
Hekili addon is not persistent. Goes off every reload or load into game.

### ISSUE THREAD

**Issue by blecaplol** [SFX-WoW/Masque#157]
**Game Version**
Retail 9.1.5
**Add-On Version**
Latest
**Describe the Issue**
An external addon call Hekili is not always 
[Description]

**Steps To Reproduce**
You can just load it, select the skin, for me Dream and then reload again. It went back to default now.

**Error Message**
_If applicable, provide any error messages._

```text
[Error Message]
```

**Screenshots**
_If applicable, add screenshots to help demonstrate the issue._

[Screenshots]

**Additional Information**
_Provide any additional information that may be relevant to this issue._

[Information]

**Comment by StormFX** [comment]
This is likely an issue with your save variables for that add-on. Try deleting them.

**Comment by Focusmighty** [comment]
> This is likely a write issue with your save variables for Masque. Try deleting them.

I just did and no joy. Still went back default after reloading.

**Comment by StormFX** [comment]
Ok. Try selecting the "Global" section of the skinning tab in Masque and clicking the reset button. Then, select a different skin, reload and see if it sticks. Then you can re-select your preferred skin. If that doesn't work, it may be an issue with how Hekii is implementing it. It works with everything else on my end, so it's not Masque issue.

**Comment by Focusmighty** [comment]
> Ok. Try selecting the "Global" section of the skinning tab in Masque and clicking the reset button. Then, select a different skin, reload and see if it sticks. Then you can re-select your preferred skin. If that doesn't work, it may be an issue with how Hekii is implementing it. It works with everything else on my end, so it's not Masque issue.

Ok I did ask instructed. Reset, select a different skin "Zoomed" followed by /reload it i still the same. Again, I immediately click Enable twice on Hekili and the skin came back differently. This has never happened before but until an update somewhere in between, i'm just saying what I noticed. It's ok thx for help.
