### ISSUE TITLE
Bug: Error Message

### ISSUE THREAD

**Issue by Cimji** [SFX-WoW/Masque#162]
### Game Flavor

Retail

### Game Version

9.2.0

### Add-On Version

9.2.0

### Description
Not sure what is the problem, just getting an error message.

### Steps To Reproduce

1. Made sure I have it updated
2. Uninstalled it and downloaded it again
3. It on all characters, even just with the base Masque addon

### Error Message

```
9x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua:518: Usage: AceConfigDialogTooltip:SetText("text" [, color, wrap])
[string "=[C]"]: in function `SetText'
[string "@Masque\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:518: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:501>
[string "=[C]"]: ?
[string "@Masque\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Masque\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Masque\Libs\AceGUI-3.0-41\widgets\AceGUIWidget-ColorPicker.lua"]:42: in function <...Libs\AceGUI-3.0\widgets
\AceGUIWidget-ColorPicker.lua:41>
```

### Screenshots

![image](https://user-images.githubusercontent.com/102595308/160605436-f90c3ca3-dd65-4959-96b1-1c10c15239f8.png)

**Comment by Cimji** [comment]
No, it seems that i can't get the hole error.

**Comment by Cimji** [comment]
Only the base masque addon, and not the other masque skins, like cirque

**Comment by StormFX** [comment]
No, I mean with Masque as the only add-on installed/enabled.

**Comment by StormFX** [comment]
The problem with some add-ons is that they share libraries. Often, when an add-on uses a shared library and it throws an error, that error gets propagated to another add-on. Disable everything but Masque and then enable add-ons one at a time, reloading each time, until the error returns. That's your culprit.

**Comment by StormFX** [comment]
@Cimji Any update on this?

**Comment by Cimji** [comment]
@StormFX Hi, as far as I can tell it happens when Elvui is on. 

5x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'PartyMemberFrame1:Hide()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Hide'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1267: in function <ElvUI\Core\Modules\UnitFrames\UnitFrames.lua:1257>
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1343: in function `DisableBlizzard'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1180: in function `UpdateAllHeaders'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:961: in function `HandleSmartVisibility'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:966: in function `?'
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>

5x [ADDON_ACTION_BLOCKED] AddOn 'Masque' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\SecureStateDriver.lua"]:10: in function <FrameXML\SecureStateDriver.lua:8>
[string "=(tail call)"]: ?
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1092: in function `CreateAndUpdateHeaderGroup'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1184: in function `UpdateAllHeaders'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:961: in function `HandleSmartVisibility'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:966: in function `?'
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by StormFX** [comment]
The first batch is from ElvUI, though that could just be propagation. The second set is a cascade from the first. Out of curiosity, can you disable any ElvUI module that isn't affected by Masque so that _only_ Masque and those portions of ElvUI are active?

**Comment by StormFX** [comment]
Have you found a resolution for this?
