### ISSUE TITLE
Masque not Working

### ISSUE THREAD

**Issue by Shagora** [SFX-WoW/Masque#22]
Hi Storm. I have a problem whit your creation . I use Bartender4 but, after the reset complete of pc, doesn't work. Sorry for my english, i'm italian guy. I need your big Addon and i belive in you. Help me, please! 

The error:

e: Interface\AddOns\Masque\Core\Options.lua:237: bad argument #2 to 'format' (string expected, got no value)
Time: 02/14/18 21:43:30
Count: 1
Stack: Interface\AddOns\Masque\Core\Options.lua:237: bad argument #2 to 'format' (string expected, got no value)
[C]: ?
[C]: in function `format'
Interface\AddOns\Masque\Core\Options.lua:237: in function `GetOptions'
Interface\AddOns\Masque\Core\Options.lua:131: in function `UpdateOptions'
Interface\AddOns\Masque\Core\Options.lua:77: in function `LoadOptions'
Interface\AddOns\Masque\Core\Options.lua:99: in function `ShowOptions'
Interface\AddOns\Masque\Masque.lua:121: in function `OnClick'
...e\AddOns\Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116: in function <...e\AddOns\Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116>

Locals: 

Message: Interface\FrameXML\InterfaceOptionsFrame.lua:434: Usage: InterfaceOptionsFrame_OpenToCategory("categoryName" or panel)
Time: 02/14/18 21:43:38
Count: 11
Stack: Interface\FrameXML\InterfaceOptionsFrame.lua:434: Usage: InterfaceOptionsFrame_OpenToCategory("categoryName" or panel)
[C]: ?
[C]: in function `assert'
Interface\FrameXML\InterfaceOptionsFrame.lua:434: in function `InterfaceOptionsFrame_OpenToCategory'
Interface\AddOns\Masque\Core\Options.lua:103: in function `ShowOptions'
Interface\AddOns\Masque\Masque.lua:121: in function `OnClick'
...e\AddOns\Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116: in function <...e\AddOns\Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116>

Locals:

**Comment by StormFX** [comment]
Not sure what your setup is but disable ALL add-ons except Masque and Bartender 4, making sure both have their embedded libraries. Also keep in mind that if you're using a custom UI, I do not offer support as the authors tend to modify the included packages.

**Comment by Shagora** [comment]
Not work man. I try to set only Masque and Bt4, but nothing.
My addons list is:

AdvanceInterfaceOptions
Bagnon
Bartender4
DBM
DBM challenge
GTFO
Kibs Item Level
Masque
MoveAnything
OmniCC
Postal
Skada
TipTac
World Quest Tracker

**Comment by StormFX** [comment]
Not sure what to tell you. I just logged in and everything is working. Make sure you've disabled everything except Masque and Bartender4.

**Comment by Shagora** [comment]
Hi. Yes, i did but doesn't work. I also tried the complete reset of the computer but it always gives me that error string:

Message: Interface\AddOns\Masque\Core\Options.lua:237: bad argument #2 to 'format' (string expected, got no value)
Time: 02/16/18 17:42:50
Count: 1
Stack: Interface\AddOns\Masque\Core\Options.lua:237: bad argument #2 to 'format' (string expected, got no value)
[C]: ?
[C]: in function `format'
Interface\AddOns\Masque\Core\Options.lua:237: in function `GetOptions'
Interface\AddOns\Masque\Core\Options.lua:131: in function `UpdateOptions'
Interface\AddOns\Masque\Core\Options.lua:77: in function `LoadOptions'
Interface\AddOns\Masque\Core\Options.lua:99: in function `ShowOptions'
Interface\AddOns\Masque\Masque.lua:121: in function `OnClick'
...e\AddOns\Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116: in function <...e\AddOns\Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116>

Locals:

**Comment by StormFX** [comment]
This is related to a faulty translation, which should be fixed in the next version. Closing.
