### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by MerGaming** [SFX-WoW/Masque#235]
Hello when i enable Masque my sound on Weakaura is not working anymore

thing i did:
removed and reinstalled masque
downloaded bug tracker : no bugs 
---------------------------------------
so when i disable Masque the weakaura sound is working 
i hope there is a simple solution for this 

thanks

**Comment by StormFX** [comment]
Masque doesn't do anything that affects any sound in any way. Either your WA settings are off or there's an issue in WeakAuras.
