### ISSUE TITLE
Question: Fonts, other addons

### ISSUE THREAD

**Issue by ssbb112V** [SFX-WoW/Masque#237]
### Game Flavor

TBC Classic

### Game Version

3.4.0 or 2.5.4

### Add-On Version

9.2.7

### Describe the Improvement

When I install masque, I get conflicts with bartender and other addons. This manifests itself in the fact that all fonts (bindings, macro names) on bartender become less beautiful.
I also use the Lorti UI addon (darkens the bartender icons).
This is what my spellbar looks like:
![image](https://user-images.githubusercontent.com/106621275/188617810-8f8a96a5-0e8d-498e-93aa-49cfe163e7b1.png)

Now i install masque and turn off all settings:
![image](https://user-images.githubusercontent.com/106621275/188617749-d68936ef-f44a-43a6-b9cf-e67efa31edee.png)

My settings masque all disable, but my interface still change:
![image](https://user-images.githubusercontent.com/106621275/188617267-6f70b98b-e48f-4dda-83e5-f54251cf0701.png)
![image](https://user-images.githubusercontent.com/106621275/188617300-b38125dd-b880-4e31-aa6b-b8eb9a30e899.png)

I really want to start using masque (it can make circle icons on WeakAuras with the raeli skin), but masque messes up my bartender.

Is it possible to FULLY remove the bartender(and other) settings from the masque, leaving only the weak auras? Maybe you can tell me which files&folders need to be deleted for this.

**Comment by ssbb112V** [comment]
how completely disable Bartender4?
I posted screen with my settings and i've reload many times
It didn't solve the problem, that's why I wrote

**Comment by StormFX** [comment]
This is an issue with LortUI. It checks to see if Masque is loaded and if it is, it doesn't apply its own skin. I would suggest asking the author to either update the check code to see if Bartender4/Dominos is disabled in Masque and _then_ disable the LortUI skinning or to put together a Masque skin for LortUI.
