### ISSUE TITLE
Bug: Icons Too Small

### ISSUE THREAD

**Issue by rml9ty** [SFX-WoW/Masque#247]
### Game Flavor

Retail

### Game Version

10.0

### Add-On Version

10.0.0-Alpha

### Description

for some reason my WeakAura buttons appear super small in size, like 50% as big as before. I'm using the same settings as on live.

any idea of why that might be?

screenshots retail vs ptr. same settings.

### Screenshots

https://imgur.com/a/BHHCgmg

**Comment by StormFX** [comment]
What skin are you using?

**Comment by rml9ty** [comment]
I'm using "Caith". On live 'Caith' is exactly the same size as 'Default'. On PTR choosing Caith over Default the icons shrink, by like almost a third of their original size.

**Comment by rml9ty** [comment]
Same thing with 'Serenity'. It also shrinks on ptr.

**Comment by StormFX** [comment]
This is because of the change in the default button size. On live, buttons are 36 x 36, whereas on the PTR they're 45 x 45. So, for example, the size of Caith's 'Normal` texture is 42 x 42. Masque scales the textures based on the button's size relative to the default button size, A newly-created WeakAura is 64 x 64, so:

#### Live
`64 / 36 * 42 = 75`

#### PTR
`64 / 45 *42 = 60`

While this may be a bit inconvenient in that buttons larger than 45 x 45 will have to be changed in their respective add-ons for the PTR, it does ensure that smaller buttons are scaled properly. It's a bit of a conundrum since Masque has to account for scaling, the add-on dictates the button's actual size and skins dictate the texture sizes.

**Comment by rml9ty** [comment]
Hm... I'm not entirely sure that I fully understand what this means going forward. does this 'simply' mean I have to manually edit all my WA icons to account for this, as this is... "how it is" from now on?

**Comment by StormFX** [comment]
It means that, until I figure out a better way to handle scaling, Dragonlight users will need to adjust their button sizes for add-ons that use custom frames (Eg, WeakAuras). I'm hoping to have something worked out before the pre-patch, but no guarantees. Keep in mind that this is an alpha, so there will be issues that need to be resolved.

**Comment by rml9ty** [comment]
Alright, I see. I was just wondering whether to already start adjusting everything now. But it sounds like, if I interpret what you said correctly, I should rather wait. I see myself changing everything and you coming up with a solution the second I'm done 😁

Thanks for keeping Masque alive. Would be super weird not having it. ♥️

**Comment by jamby** [comment]
This is also the case for FlatSquares, but from reading your response it seems that is probably assumed. Here's hoping for a quick fix. Thanks for the addon!

**Comment by StormFX** [comment]
@rml9ty Yeah, it'd be best to hold off changing anything just yet. It's a tricky problem but I may be able to fix it.

**Comment by Marcethemage** [comment]
Updating the LUA file of the single skin worked for me, at least with ELVUIesque skin, you need to change the size of every element but it takes 2 minutes, should be a simple update on the skin-developer side.

**Comment by rml9ty** [comment]
> Updating the LUA file of the single skin worked for me, at least with ELVUIesque skin, you need to change the size of every element but it takes 2 minutes, should be a simple update on the skin-developer side.

great tip! just did it and it works perfectly. just took every number in there times 1,25 and voila *thumbs up*

**Comment by StormFX** [comment]
Just to let you all know, I'll be reverting this change until a later date when I can implement a better scaling method.

**Comment by StormFX** [comment]
As of Alpha-3, this now only affects _Retail_ (DF) Action buttons, since they're the only ones that increased in size.
