### ISSUE TITLE
Question: Skins not Applying to Default Buttons

### ISSUE THREAD

**Issue by Tovrin** [SFX-WoW/Masque#252]
### Game Flavor

Retail

### Game Version

10.0

### Add-On Version

10.0

### Description

I've just switched across from Bartender to the new standard WoW buttons bars and Masque doesn't appear to work with it.  (Apologies if it's not intended to, but I wasn't sure).

**Comment by StormFX** [comment]
Masque doesn't support the default UI. It's basically a library with a GUI. It can only skin buttons that it's told to skin.

**Comment by Tovrin** [comment]
Ok.  Thanks.

**Comment by Tovrin** [comment]
Not an issue.
