### ISSUE TITLE
Im not sure where to ask 

### ISSUE THREAD

**Issue by blecaplol** [SFX-WoW/Masque#259]
### Game Flavor

Retail

### Game Version

10.0.0

### Add-On Version

9.2.7

### Description

Hi im not sure where to ask but im using the blizzard default unitframe and actionbar. does masque support skinning?

**Comment by zcourge** [comment]
There's an addon called "Masque Blizzard Bars Revived" that does just that!

**Comment by blecaplol** [comment]
> There's an addon called "Masque Blizzard Bars Revived" that does just that!

I tried it and it lags when I change actionbar page. pretty big lag.

**Comment by StormFX** [comment]
Because of the way Masque works, it cannot support the default interface. You'll need to find a third-party add-on that provides that feature.

Also, 9.2.7 is not compatible with Dragonflight. Update to the latest beta.
