### ISSUE TITLE
Question: Positioning / Overlapping

### ISSUE THREAD

**Issue by XeeLiao** [SFX-WoW/Masque#260]
Hi,

there is this problem here, when i move 1 point up in bartender4 it becomes as shown, dont know if this has anything to do with Masque or if it is just because of the new scaling.

Best Regards

![positioning](https://user-images.githubusercontent.com/41451315/198583768-2a4572a7-d54d-4f73-8aa7-d5bc6fa2e10f.png)

**Comment by StormFX** [comment]
I don't understand what I'm looking for in that image.

**Comment by XeeLiao** [comment]
Sorry, here this part, it is also stretching Icons


![positioning](https://user-images.githubusercontent.com/41451315/198696990-84fb56c8-e4bb-4297-840e-e7430e4a9d22.png)

**Comment by StormFX** [comment]
Had to zoom in to really see it. So what you're seeing is the backdrop overlapping because you've nudged that particular bar a pixel or so too high. It's not aligned with the bar to the right of it. As far as minor stretching of textures, this is to be expected with the way the game renders.
