### ISSUE TITLE
Bug: SetVertexColor Error

### ISSUE THREAD

**Issue by nancikennedy** [SFX-WoW/Masque#262]
### Game Flavor

Retail

### Game Version

Latest

### Add-On Version

10.0.0 Beta 3

### Description

I was moving the mouse across the game window and noticed my bug error count incremented. Not sure what triggered it.

### Error Message

```text
2x Usage: self:SetVertexColor(color [, a])
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-ColorPicker.lua"]:105: in function `SetColor'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1368: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1101>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1630: in function `FeedGroup'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1555: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1539>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1666: in function `FeedGroup'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1910: in function `Open'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1938: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1936>
...
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-BlizOptionsGroup.lua"]:20: in function <...GUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua:19>
[string "=[C]"]: in function `Show'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:799: in function `DisplayLayout'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:758: in function `DisplayCategory'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:725: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:721>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/SharedXML/Settings/Blizzard_CategoryList.lua"]:136: in function <...terface/SharedXML/Settings/Blizzard_CategoryList.lua:134>
```

**Comment by StormFX** [comment]
Can you clear your errors and see if you can trigger it again?

**Comment by nancikennedy** [comment]
I'm pretty sure this time, it happened when I was interacting with a color picker

1x Usage: self:SetVertexColor(color [, a])
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-ColorPicker.lua"]:105: in function `SetColor'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1368: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1101>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1630: in function `FeedGroup'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1555: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1539>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1666: in function `FeedGroup'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1910: in function `Open'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:1938: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1936>
...
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:758: in function `DisplayCategory'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:725: in function `SelectCategory'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:307: in function `OpenToCategory'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:88: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:85>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsInbound.lua"]:25: in function <...face/SharedXML/Settings/Blizzard_SettingsInbound.lua:24>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/SunnArt/SunnArt_Core.lua"]:15: in function `OnClick'
[string "@Interface/AddOns/Bazooka/Bazooka.lua"]:1425: in function <Interface/AddOns/Bazooka/Bazooka.lua:1422>

**Comment by StormFX** [comment]
Can you be more specific? Are you using a color picker add-on? What add-on were you changing colors for? Etc.

**Comment by StormFX** [comment]
Also, as far as I'm aware, Bazooka is broken in Dragonflight. Disabled it to make sure it's not the culprit.

**Comment by nancikennedy** [comment]
### It is Sunn Art. Providing this info as an FYI for you...

I unloaded everything but Masque and Bazooka (using the r331 alpha released today): Everything was fine.

I then did the same with Sunn Art (3.93). As soon as I clicked on Sunn Art in the Game Menu:Options:Addons List tab, it generated the SetVertex error.

Message: Usage: self:SetVertexColor(color [, a])
Time: Fri Oct 28 15:52:59 2022
Count: 1
Stack: Usage: self:SetVertexColor(color [, a])
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua"]:105: in function `SetColor'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1368: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1101>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1630: in function `FeedGroup'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1555: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1539>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1666: in function `FeedGroup'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1910: in function `Open'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1938: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1936>
...
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua"]:20: in function <...GUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua:19>
[string "=[C]"]: in function `Show'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:799: in function `DisplayLayout'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:758: in function `DisplayCategory'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:725: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:721>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/SharedXML/Settings/Blizzard_CategoryList.lua"]:136: in function <...terface/SharedXML/Settings/Blizzard_CategoryList.lua:134>

Locals: <none>

Clicking on any tab in the Sunn Art options panel other than Global options, and then clicking back on Global options produces a new slightly different error.

Message: Usage: self:SetVertexColor(color [, a])
Time: Fri Oct 28 15:59:52 2022
Count: 2
Stack: Usage: self:SetVertexColor(color [, a])
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua"]:105: in function `SetColor'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1368: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1101>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1630: in function `FeedGroup'
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1555: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1539>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals: <none>

**Comment by StormFX** [comment]
Thanks. The references to Masque you're seeing are likely just library propagation. Glad you got it figured out!

**Comment by nancikennedy** [comment]
Thanks for you patience as I figured it out. I will update the Sunn Art people.
