### ISSUE TITLE
Question: Unable to Apply Skins

### ISSUE THREAD

**Issue by eightflat** [SFX-WoW/Masque#267]
I feel like I'm missing something obvious here, but ever since 10.0, my Masque options just look like this. I can't actually select which skin to apply, it just tells me compatibility and information about the author. Before the recent changes, I was able to select different button elements and apply Masque skins to them. All my previous settings are still applied, but I can't make any new ones. Has the functionality moved somewhere else, or is this like a temporary limitation while the addon is updated? Thanks for all your work.

![image](https://user-images.githubusercontent.com/42418384/198856137-07c9e6fe-8bb5-4390-9cbc-728a806ef2d2.png)

**Edit**: Oh... speak of the devil. As soon as I clicked another addon's options, the plus sign appeared to the left of Masque and I'm able to do everything as usual. I'm pretty sure this plus sign wasn't visible until I clicked another addon's options, so perhaps this counts as a bug?

**Comment by kstange** [comment]
I'm pretty sure this is an interface bug with WoW at the moment.  Plugins that change their menu contents to have submenus don't show up until the frame is redrawn.  I imagine it will eventually be fixed by Blizzard.

**Comment by StormFX** [comment]
Yeah, if the additional options don't show, you can either click the `Game` tab and back or click the `+` next o another add-on. I am curious to know how that happened in your case, because I made all of the options pre-load for Dragonflight users who aren't using the stand-alone GUI.
