### ISSUE TITLE
Question: Masque 10.0 Resizing Action Bar Buttons

### ISSUE THREAD

**Issue by Bowktom** [SFX-WoW/Masque#270]
### Game Flavor

Retail

### Game Version

10.0

### Add-On Version

10.0.0

### Description

Since the 10.0 update, the masque addon is resizing my action bar buttons to a very small size, when i disable the addon they return to normal size. I had a look in the settings but see no option to alter the size.

### Screenshots

https://snipboard.io/SH1gZz.jpg
https://i.snipboard.io/s5ylCx.jpg

**Comment by StormFX** [comment]
The changes are listed in the change log. For now, you can either turn on Classic Scaling in Masque's Options under `General Settings`/`Interface` or you can download the latest beta, which reverts the scaling changes.
