### ISSUE TITLE
Question: Masque Not Working with Default UI

### ISSUE THREAD

**Issue by greenstones** [SFX-WoW/Masque#271]
### Game Flavor

Retail

### Game Version

10.0.0

### Add-On Version

10.0.0

### Description

While the addon explains that it can change the look of the UI bars - it does not actually do so if you do not have a 3rd party bar addon loaded.

When trying to use it with the new built in UI no changes occur when you switch skins.

Not sure if this is intended or if its not enabled yet for the Dragonflight Built in UI.

### Error Message

```text
No errors occur - nothing changes - basically trying to clarify function of addon to see if that is the intended function.
```

**Comment by StormFX** [comment]
> While the addon explains that it can change the look of the UI bars - it does not actually do so if you do not have a 3rd party bar addon loaded.

It does, just not blatantly:

Inside the about panel for _Masque_:

> Masque is a skinning engine **_for button-based_ add-ons**.

Similar text is found on the description page alone with the requirements:

> - An action bar, aura or inventory add-on that supports Masque.

So to clarify, Masque is a library-based skinning engine. As a library, it requires interaction from third-party add-ons to function. I apologize if this wasn't clear, as that wasn't the intent.
