### ISSUE TITLE
Bug: Default Skin Size is Incorrect

### ISSUE THREAD

**Issue by kstange** [SFX-WoW/Masque#273]
### Game Flavor

Retail

### Game Version

10.0.0

### Add-On Version

10.0.1

### Description

In Masque 10.0.1 with the default scaling settings, if I select the Disable option for a group or select the Default skin, it ends up making the buttons overflow their container and overlap rather than correctly show the default appearance.  If the Disable option is checked on initial load, the buttons look normal.

### Screenshots

Masque "Default" or post-UI load Disabled state:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/8593622/198908976-064d6848-18bf-40ac-8db8-bb181752ced8.png">

Disabled state on initial UI load:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/8593622/198909008-2d3014ff-4194-4c92-919e-1ee47eecdc22.png">

### Notes

As with my other issues, I am seeing this with my mod applying the skin to the native action bars, but I suspect this is related to reverting to the "classic scaling" without updating the skin.

**Comment by StormFX** [comment]
The default action buttons, at their native size are 45 x 45 in Dragonflight. Reverting the scaling reduced the scale factor to 36, therefore the size every skin is increased by 125% when applied to those buttons. Eg, an icon whose skin definition is 36 x 36 will be scaled up to 45 x 45. The Default Dragonflight skin is defined with 45 as the base, so it gets increased to ~56 x 56.

**Comment by StormFX** [comment]
@Xugos The upcoming release (now in beta) reverses the change that caused that and removes that option, just so youknow.

**Comment by Xugos** [comment]
oh ok :)
