### ISSUE TITLE
Bug: Text Overflowing Buttons in Skins

### ISSUE THREAD

**Issue by kstange** [SFX-WoW/Masque#275]
### Game Flavor

Retail

### Game Version

10.0.0

### Add-On Version

10.0.1

### Description

I saw a report from a user of MasqueBlizzBars that HotKey text is overflowing buttons.  This seems to be a skin related behavior, that HotKey and Name have no width or height set so they just take up whatever space they want.  This can result in the mess in the screenshot, but I'm not sure if this behavior is intended.  I see this with all the included skins for HotKey, and with Caith for the Name as well.

### Screenshots

<img width="271" alt="image" src="https://user-images.githubusercontent.com/8593622/199111796-3f24dcb5-9090-427e-bdbd-610e583ea3f5.png">

**Comment by StormFX** [comment]
See #274. The vase skins have been fixed. I have as yet to go through the stand-alone skins.

**Comment by StormFX** [comment]
Also, just wanted to say thanks for all your input. Feel free to join [my Discord](https://discord.gg/DDVqkd6), :p

**Comment by kstange** [comment]
I'm glad that you aren't finding me to be an annoyance. :P

**Comment by StormFX** [comment]
I'm not. I can't find all the issues myself. :P Haven't even had time to put talents on my characters yet. >.<
