### ISSUE TITLE
Bug: Lua Error

### ISSUE THREAD

**Issue by agentschmitt** [SFX-WoW/Masque#288]
### Game Flavor

Retail

### Game Version

10.0.2

### Add-On Version

10.0.2

### Description

Got lua error

### Error Message

```text
1x ...nfig-3.0/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:330: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:330: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:310>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1114: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1137: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1639: in function `FeedGroup'
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1564: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1548>
[string "=[C]"]: ?
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:508: in function `SetSelected'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:185: in function <...ibs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:181>
```

**Comment by StormFX** [comment]
I'm going to need more information. What were you doing when the error occurred, what add-ons do you have installed, etc.

**Comment by azuraji** [comment]
It's probably not related to Masque. The error originates from a library that is included with Masque, so it could be any arbitrary addon that you're using.

**Comment by StormFX** [comment]
That was my thinking, as I haven't experienced anything similar.

**Comment by agentschmitt** [comment]
i will have a look when it happens next time what i did exactly and check if i can find related addon.

**Comment by StormFX** [comment]
Also make sure you've tested it with just Masque and whatever add-on(s) it's skinning enabled.

**Comment by agentschmitt** [comment]
i wasnt able to replicate the error since hours of playing, so i would close it for now.

**Comment by StormFX** [comment]
For what it's worth, the expansion introduced a _lot_ of taint and random bugs. Given that Masque uses the same libraries as dozens of other add-ons, it's most likely propagation from something else. Thanks for the report, though!

**Comment by agentschmitt** [comment]
after running some dungeons i got similar error from masque. but without constantyl reproducing it i cant say which addon as i have a really big list of addons i am using :P

1x ...nfig-3.0/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:330: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:330: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:310>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1114: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1137: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1639: in function `FeedGroup'
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1564: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1548>
[string "=[C]"]: ?
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:508: in function `SetSelected'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:185: in function <...ibs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:181>

so i think issue is not related to your addon

**Comment by StormFX** [comment]
All that really tells me is that Masque's version of Ace3 is the last to get loaded, so it's the most recent. If you're running any out of date add-ons, they may be at fault.
