### ISSUE TITLE
Feature Request: Group Notes

### ISSUE THREAD

**Issue by kstange** [SFX-WoW/Masque#291]
### Game Flavor

Retail

### Game Version

10.0.2

### Add-On Version

10.0.3

### Describe the Improvement

I'd like an option in Masque to add notes to Groups which can appear in the mouseover tooltip for the group name, and just above the "disable" checkbox in the group's settings panel.  The purpose of this note would be to provide additional clarifying text, such as what buttons are included in the group or any tips about skinning options for the group.

It might also be nice to provide a way to set this on the addon-level panel.

### Example Code

In Discord, a suggested method for Groups was discussed:

``` lua
local Group = LibStub("Masque"):Group("Addon", "Group")
Group.Notes = L["This allows the skinning of only these buttons. Those buttons won't be skinned."]
```

### Screenshots

Ideally the text would appear in this tooltip:

![image](https://user-images.githubusercontent.com/8593622/208805313-41a35b70-7841-4e71-b7db-04d471bc01ee.png)

And in this panel location:

![image](https://user-images.githubusercontent.com/8593622/208805636-382b3c08-e191-488d-805c-9f90be65e20d.png)

**Comment by StormFX** [comment]
For the panel itself, I suppose I could use an inline group with a border and "Notes" header, similar to how "Backdrop" is in the above screenshot. Shouldn't be too difficult to add. I'll look into it.
