### ISSUE TITLE
Question: Shadow for fonts

### ISSUE THREAD

**Issue by sMuve** [SFX-WoW/Masque#300]
Hi there,

not sure, if this is the right place to ask, but I would like to manipulate the shadow of fonts (e.g. duration on buffs).
Is this possible with Masque? I red the doc, but did only read something about borders/shadows for buttons.

I was able to manipulate the positioning of the duration, but not the shadow as you can see here
![image](https://user-images.githubusercontent.com/25771494/211928793-9707f1dd-859a-4a23-8644-75c9c4c902c1.png)

Thank you in advance <3

**Comment by StormFX** [comment]
Masque doesn't control the font style, size or effects. Only the position.

**Comment by sMuve** [comment]
Thank you for the super fast reply!
