### ISSUE TITLE
Masque 10.0.7 Warning Thread

### ISSUE THREAD

**Issue by StormFX** [SFX-WoW/Masque#319]
This issue is for users reporting a warning from Masque about add-ons using deprecated methods. If the add-on(s) you're receiving a message for is not listed below, please post with the name(s) of the add-on(s) so that I can notify the author(s).

#### Add-Ons Giving Warnings

- [HidingBar](https://github.com/sfmict/HidingBar) - Fixed in sfmict/HidingBar@6642daa.
- [oPie Masque](https://github.com/phanx-wow/OPieMasque) - Outdated. Use [this version](https://github.com/kstange/OPieMasque).

**Comment by StormFX** [comment]
> HidingBar

Added. Thanks for the report!

**Comment by StormFX** [comment]
> [OPie Masque](https://github.com/phanx-wow/OPieMasque)

Are you using the [updated version](https://github.com/kstange/OPieMasque)?

**Comment by azuraji** [comment]
Thank you!

**Comment by StormFX** [comment]
You may need to adjust a setting or something. As far as I'm aware, it should work.

**Comment by azuraji** [comment]
Does it work for you? I didn't find any setting that would make it work... It's as if this addon isn't seen by Masque

**Comment by StormFX** [comment]
Maybe there's a conflict with the old one. Disable any versions of OPie Masque and then go to General Settings > Developer > Clean Database.

It's working fine for me:
![image](https://user-images.githubusercontent.com/1234928/231259618-216673ba-4815-442e-b46c-ef3e4af4eaef.png)

**Comment by azuraji** [comment]
Unfortunately that did not help. Are you using the latest Yuzu 7?

**Comment by StormFX** [comment]
I don't know what "Yuzu" is.

**Comment by azuraji** [comment]
OPie uses code names in addition to versions, see e.g. https://www.curseforge.com/wow/addons/opie/files

**Comment by StormFX** [comment]
I guess I am:

![image](https://user-images.githubusercontent.com/1234928/231310498-2d5dcd35-0c80-4c3c-90dc-86b6a23c298f.png)

All I can suggest is that you disable everything but OPie, OPie Masque (The one from SimGuy) and Masque. It's working on my end and it's not issue with Masque.

**Comment by azuraji** [comment]
Found the setting to make it work. It used to be called "OPieMasque" but was changed to "Masque" which made it stop working. Manually changed it back in the LUA code.

**Comment by StormFX** [comment]
> Found the setting to make it work. It used to be called "OPieMasque" but was changed to "Masque" which made it stop working. Manually changed it back in the LUA code.

If that's the case, you probably just needed to select "OPie" first, reload and then select "Masque". It was probably reading an old "OPieMasque" setting instead of the "Masque" setting.
