### ISSUE TITLE
Bug: "Action Blocked" When Opening Adventure Guide

### ISSUE THREAD

**Issue by Syzuna** [SFX-WoW/Masque#325]
### Game Flavor

Retail

### Game Version

10.1.0

### Add-On Version

10.1.0

### Description

I am redoing my interface at the moment.
I decided to use Masque again to skin some things.
Now everytime I open the Adventure guide I get an error message/warning that "Masque has been blocked from an action only available to the Blizzard UI"

### Error Message

```text
Masque has been blocked from an action only available to the Blizzard UI
```

### Steps to Reproduce

1. Open Adventure Guide
2. Get a popup with the provided error message

### Screenshots

![Wow_qgqYn94WGr](https://user-images.githubusercontent.com/22714301/235953392-7ab65846-fe20-40fa-91cd-e7fa29a1ce06.png)

**Comment by StormFX** [comment]
If you wouldn't mind, can you test this with _only_ **Masque** enabled? Also test it with whatever add-on(s) you're skinning with **Masque**.

**Comment by Syzuna** [comment]
Interesting enough I cant reproduce either today after a new round of addon updates.
So I guess it was just disguised as a Masque error as you suspected.

**Comment by StormFX** [comment]
With all the changes since 10.0, there are a _lot_ of random things can cause taint, so it's often really difficult to narrow down. Most authors generally avoid anything that's know to cause taint.
