### ISSUE TITLE
Feature: Options to Use Old Spell Alerts and Cooldowns

### ISSUE THREAD

**Issue by ANaPhOrAX** [SFX-WoW/Masque#332]
### Game Flavor

Retail

### Game Version

10.1.5

### Add-On Version

10.1.1

### Describe the Improvement

with 10.1.5 blizzard has changed the look of the proc flash around action bar buttons. they've also added a swirly gcd timer thing which plays around all action bar buttons after using an ability.

my question is as follows: would it be possible for you to add something to revert all these changes? or would that make no sense? maybe it's more something i.e. Dominos could implement? I don't know though. I figured I'd ask.

I hate the new look so much that if there's no fix I'll legitimately stop playing the game. And for me it's 'just' a sensory overload issue, but I've actually seen various people with disabilities complaining about this, too.

If there's anything you could do, it would be greatly appreciated.

**Comment by StormFX** [comment]
I suppose I could look into it, though no guarantees.

**Comment by ANaPhOrAX** [comment]
Hey there, little update: I noticed Tuller actually wrote a little bit of code on an issue someone started on the Dominos repo. I figured I would link it here. Not that I don't think you could write it yourself, but maybe it could save you some time, I don't know.

https://github.com/tullamods/Dominos/issues/762#issuecomment-1633310185

**Comment by ANaPhOrAX** [comment]
https://i.imgur.com/A520G8j.jpg here's how the flash looks for me atm btw. just gross with the extra spacing. I have the scaling tweaked btw because with dragonflight something about the scaling got changed, making all my actionbars way bigger when I first logged in. so I had to make them smaller, but if I did that via dominos, the keybindings became so small they were illegible. so iirc to keep the keybinding the same size I increased the scaling with dominos, and then decreased it in masque.. and the end result looked about the same as pre-DF. sigh

**Comment by StormFX** [comment]
I commented over yonder.

**Comment by StormFX** [comment]
I've added animation options to Masque in the beta. Adding the old-style would be regressive, so I won't be adding those. You seem to be using the **Dominos** skin, which will be updated to have the new animations tweaked to fit, but it won't account for any custom tweaks you may have done.

If you could give the current beta a go and see how that plays, I can get this closed. It'll be Monday or so before I get the skins updated, in which case further references to the skins themselves can be made in their respective repos.
