### ISSUE TITLE
Bug: Empty buttons remain visible when they should not

### ISSUE THREAD

**Issue by Zasz333** [SFX-WoW/Masque#333]
### Game Flavor

Retail

### Game Version

10.1.5

### Add-On Version

10.1.1

### Description

When we open the spellbook or talents all empty buttons on the interface are visible even when the option "always show buttons" in edit mode is not enabled.

When closing the spellbook or talents all empty buttons are supposed to hide again. But often they remain visible.

The only way to solve this is to reload the UI or log out and back in.

I tested on a toon without masque and didnt get this problem.

### Error Message

```text
None given.
```

### Steps to Reproduce

Open spellbook
Close spellbook
Empty buttons remain visible

**Comment by StormFX** [comment]
This sounds like an issue with whatever add-on you're using, as Masque does not do anything to affect button visibility.

**Comment by Zasz333** [comment]
I dont use an addon for button bars. Except for masque.

**Comment by Zasz333** [comment]
I checked again to be sure. Its possible its not directly masque but masque blizzard bars which enables masque to skin the built-in wow action bars.

**Comment by StormFX** [comment]
They could have changed something that SimGuy missed. I'll look into it.

**Comment by kstange** [comment]
This is cross posted [here](https://github.com/kstange/MasqueBlizzBars/issues/3), but I haven't been able to reproduce it.
