### ISSUE TITLE
WeakAuras skin not showing properly on aura "Shadowflame Crests"

### ISSUE THREAD

**Issue by raptormama** [SFX-WoW/Masque#344]
### Game Flavor

Retail

### Game Version

10.1.7

### Add-On Version

10.1.7

### Description

Running with ElvUI 13.44, Masque 10.1.7, and WeakAuras 5.8.1

![weakauras-aura-masque-bug](https://github.com/SFX-WoW/Masque/assets/5473082/a684d2d7-9068-4248-be56-9720a5e83edd)

As shown here, skins -- I'm attempting to use [CleanUI](https://www.curseforge.com/wow/addons/buttonfacade-cleanui) but the issue persists also with [ElvUI](https://www.curseforge.com/wow/addons/masque-elvui) and other skins -- aren't applying correctly to the icons in the [Shadowflame Crests aura](https://wago.io/WhsQ8uidK/6) other than the top small one (Flightstones).

Masque skins do seem to properly skin other auras I've got in WeakAuras, just not this one.

### Steps to Reproduce

This issue happens in normal use (in zones I've enabled it in, when the aura appears, the issue is present). It persists through hide/show and across game sessions.

### Error Message

I am not aware of any error messages related to this issue.

### Screenshots

A screenshot is embedded in the issue description.

### Notes

This issue does not appear to cause any functionality to stop working.

**Comment by StormFX** [comment]
WeakAuras only passes auras of the Icon type to Masque. IE, if an aura was created as any type other than "Icon", it won't be passed to Masque to be skinned.
