### ISSUE TITLE
Dominos Masque appearance disappears after stealth or mount events

### ISSUE THREAD

**Issue by BorisAneli** [SFX-WoW/Masque#348]
### Game Flavor

Classic Era

### Game Version

1.15.0.52186

### Add-On Version

10.2.0

### Description

I am using Dominos addon for action bars. Masque has support for dominos addon but I noticed, that stealth / unstealth, mount / dismount events do reset masque on dominos action bars.

Looks like this events triggers some UI update functions which do not include mask logic for some reason

### Steps to Reproduce

1. Install dominos
2. Install mask
3. Do some mask settings that are apply to dominos
4. Do mount / dismount / stealth / unstealth

Result:
After event (4) dominos bars displays without mask

Expected result:
Events does not affect appearance of dominos bars

### Screenshots

https://github.com/SFX-WoW/Masque/assets/83017159/ebbbab44-9cb5-4523-8f8d-9c105e887253

**Comment by StormFX** [comment]
- It looks like you're using the Dominos skin and just recolored the icon frame. Try a different, non-standard skin and see what happens.
- Masque doesn't handle events. If there's an issue with state changes on certain events, that would be an issue with Dominos or something else you have installed.

**Comment by BorisAneli** [comment]
Yes, it's recolored dominos skin, problem can be in skin itself?

**Comment by StormFX** [comment]
Well, some skins use default textures that might not work as expected in certain conditions. In order to analyze what's going on, you should try a skin that doesn't use default textures to eliminate the skin being "reset" as a possible culprit. Try testing with a skin like [Caith](SFX-WoW/Masque_Caith) that doesn't use default textures.

**Comment by BorisAneli** [comment]
Dominos skin looks perfect for me, all other skins have too modern look, so I wanna try to figure out whats going on, maybe Ill even try to fix it on my own. Can u please give me some clues about what's going on, why default textures can behave like this, does this logic on masque side or on dominos?
As software engineer myself I see high probability of fix in one function call in correct place (maybe on dominos side)

**Comment by StormFX** [comment]
I wasn't asking you to use a different skin, I was asking you to _try_ a different skin and see if the issue still occurs. This will give me more of an idea on where to look.

**Comment by StormFX** [comment]
You could try commenting out line 91 of `Masque_Dominos/Skins.lua` and see if that helps. Eg:

```lua
		-- UseStates = true,
```

**Comment by BorisAneli** [comment]
I checked out each default skin as well as caith skin
Сaith as well as all default skins exept "Blizzard classic" do work without any issues

WIth default "Blizzard classic" skin initial issue occurs

**Comment by StormFX** [comment]
Ok. I'll have to look into this a bit further.

**Comment by StormFX** [comment]
It is as I suspected. In Classic/Classic era, the Normal texture is having its color changed by Blizzard code whereas in Retail, this color change is applied to the Icon instead. Commenting out the `UseStates` line _does_ work, but you have `/reload` after you change it.

**Comment by BorisAneli** [comment]
Thanks a lot for help!
