### ISSUE TITLE
FRAME STRATA

### ISSUE THREAD

**Issue by xapollyon** [SFX-WoW/Masque#349]
### Game Flavor

Retail

### Game Version

10.2

### Add-On Version

latest

### Describe the Improvement

Is it possible to add a FRAME STRATA feature? This is because I have some action buttons close to my character and when combat scrolling is on, the text runs on top of the buttons.  If there was a FRAME STRATA option we could make the MASQUE action buttons on HIGH STRATA making the text go under the buttons.

Thank you

### Screenshots

I can provide if needed

**Comment by StormFX** [comment]
Text is parented directly to the button. Whatever frame level the button is on, the text will be on. Additionally, the engine draws text above textures within the same frame.
