### ISSUE TITLE
Bug: Mask Issue on Non-Item Buttons

### ISSUE THREAD

**Issue by sfmict** [SFX-WoW/Masque#359]
### Game Flavor

Retail, Classic Era, Classic Wrath

### Game Version

10.2.6

### Add-On Version

10.2.6

### Description

Hi, very cool addon, but...

```lua
-- Disable the bag slot mask in 10.0 to enable custom masks.
if CircleMask then
	local Icon = Button.icon

	if Icon then
		Icon:RemoveMaskTexture(CircleMask)
	end

	CircleMask:SetTexture()
end
```
This code (`CircleMask:SetTexture()`) disables the icon if not `Button.icon` for some minimap button addons in my addon

Mb you should use `GetNumMaskTextures` and `GetMaskTexture` to disable masks

**Comment by StormFX** [comment]
A couple of questions:
1. Which add-on is this affecting.
2. Why are minimap buttons being passed to Masque?

**Comment by sfmict** [comment]
1.Rematch
2.My addon uses the masque for skins (HidingBar)
3.I fexed it for my addon, but it's a potential bug

**Comment by StormFX** [comment]
So your add-on uses Masque for Minimap icons or?

**Comment by sfmict** [comment]
My addon grabs the minimap buttons and yes uses the masque for them.

**Comment by StormFX** [comment]
Ok. I'll look into putting something in there to specifically target the bag slots.

**Comment by sfmict** [comment]
Ahaha, ok) gl)

**Comment by sfmict** [comment]
```lua
if CircleMask then
	local Icon = Button.icon

	if Icon then
		Icon:RemoveMaskTexture(CircleMask)
                CircleMask:SetTexture()
	end
end
```
mb so

**Comment by StormFX** [comment]
Like I said, I'll look into it. It may be a bit, though.
