### ISSUE TITLE
Bug: Vehicle Exit Button with no icon loading

### ISSUE THREAD

**Issue by Lucypurr** [SFX-WoW/Masque#360]
### Game Flavor

Retail

### Game Version

10.2.6

### Add-On Version

10.2.6

### Description

Hi, like the title says, the Vehicle Exit Button don't have an icon, just a blank square/circle or others formats. I tested with the base masque and with some plugins, but none can load the icon. 

I use Elvui too, and with elvui with no masque load the icon appears.

I took some screenshot to show better the issue. Only the Vehicle Exit button don't load, the action bar, buffs and debuffs all works as it should.

In the screenshots, is the Vehicle Exit Button is on the bottom left of the screen.

Thanks.

### Error Message

```text
There are no errors on bugSack.
```

### Screenshots

![1](https://github.com/SFX-WoW/Masque/assets/116969058/15a10ffa-53d4-4b6d-a4a9-b3e08a775bd3)

![2](https://github.com/SFX-WoW/Masque/assets/116969058/95ddd59e-abca-4bde-9bd1-a7813560b708)

![3](https://github.com/SFX-WoW/Masque/assets/116969058/f14a21cd-b27a-4150-b629-61e983d5c2ec)

![4](https://github.com/SFX-WoW/Masque/assets/116969058/4e10ad55-2c78-4e20-a93b-afb88ff428ae)

![5](https://github.com/SFX-WoW/Masque/assets/116969058/63fb240f-f92a-45b5-ab3d-c30fa92dcd8c)

![6](https://github.com/SFX-WoW/Masque/assets/116969058/9b2476e0-fef3-4e53-9ec1-cec01783c542)

### Notes

I use the clean icons to better icons too. 

https://www.wowinterface.com/downloads/info25064-CleanIcons-MechagnomeEdition.html

Don't know if this may change something, but i use 2160p resolution.

**Comment by StormFX** [comment]
Expand ElvUI in the above window and see if there's a group that contains that button listed. If so, disable it. IIRC, the Exit Vehicle button is a different type of button, so ElvUI shouldn't be passing it to Masque..

**Comment by Lucypurr** [comment]
That's the only option in ElvUI that mess with Vehicle exit button, and if i disable that option no button exist/appears.

The screenshot this time is only with elvui and masque enable  (was trying to see if it was another addon messing with it)

![1](https://github.com/SFX-WoW/Masque/assets/116969058/336286a1-c956-432b-b686-7a3b06f07c64)

**Comment by StormFX** [comment]
In **Masque's options**, expand the ElvUI entry to see if there's a group that contains the vehicle exit button.

**Comment by Lucypurr** [comment]
Sorry, forgot about that one ^^

![2](https://github.com/SFX-WoW/Masque/assets/116969058/438ed15b-7781-4c48-97c4-6ae67a9ed123)

**Comment by StormFX** [comment]
Click "Disable" then reload.

**Comment by Lucypurr** [comment]
Now it shows this symbol 

![3](https://github.com/SFX-WoW/Masque/assets/116969058/9e1e4559-802e-4a89-b2dc-408313083ed9)

I see, so the options will be no icon or this symbol?

**Comment by StormFX** [comment]
If you reloaded, that must be the default icon that ElvUI uses. That's not a Masque issue.

**Comment by Lucypurr** [comment]
Yeah, i understand now what the '' shouldn't be passed to masque'' means xD.

Thanks for the patience and help ^^

**Comment by StormFX** [comment]
No problem. ;)
