### ISSUE TITLE
Masque not Skinning Buffs/Debuffs

### ISSUE THREAD

**Issue by Huf12** [SFX-WoW/Masque#366]
### Game Flavor

Retail

### Game Version

10.2.7

### Add-On Version

10.2.7

### Describe the Improvement

It does not seem possible to change icons for player buff/debuff aswell as target buff/debuff frame. Am I missing something? If this option does not exist right now it would be cool to add this in the future. cheers

**Comment by StormFX** [comment]
Masque doesn't skin the default UI. You need a third-party add-on for anything you want skinned.

**Comment by Huf12** [comment]
I see, thank you for answering
