### ISSUE TITLE
Inconsistent Border Size

### ISSUE THREAD

**Issue by Huf12** [SFX-WoW/Masque#367]
### Game Flavor

Retail

### Game Version

10.2.7

### Add-On Version

10.2.7

### Describe the Improvement

The icons on top are from omnibar addon using modern enhanced. Icons below are spells on the default action bar. Modern enhanced does not have the same border thickness on all sides. Atleast not with omnibar addon. It does for weakauras with I use also with modern enhanced. Idk if this is caused by masque, just wanted to let you know

### Screenshots

https://ibb.co/MNt9vwj

**Comment by StormFX** [comment]
The OmniBar buttons are slightly smaller, at least visually, so everything is scaled down some, including the border. You'll need to play around with OmniBar's scaling. If that doesn't solve it, you can try using Masque's scaling option for that group.
