### ISSUE TITLE
Stacks are on wrong Side with Modern Enhanced/blizzard modern

### ISSUE THREAD

**Issue by Huf12** [SFX-WoW/Masque#371]
### Game Flavor

Retail

### Game Version

10.2.7

### Add-On Version

10.2.7

### Description

Hey, if i select modern enhanced or blizzard modern stacks go to the left side. I'm using masque for BetterBlizzFrames addon

### Screenshots

https://ibb.co/wBtKh0z

**Comment by StormFX** [comment]
I'm assuming this is exclusive to buffs/debuffs?

**Comment by Huf12** [comment]
If youre referring to stacks on for example action bars then yes. It is everywhere else on the right side besides on player buffs. I dont have a way to check for player debuffs tho.

**Comment by StormFX** [comment]
To be fair, Blizzard Modern is the default action button skin so isn't really made for buffs, etc. But I'll look into tweaking it.

**Comment by Huf12** [comment]
sure. thank you

**Comment by StormFX** [comment]
Looks I had the text alignment set to "CENTER" instead of "RIGHT". Will be fixed in the next build.
