### ISSUE TITLE
Glow Effects Different in Latest Release

### ISSUE THREAD

**Issue by artazika** [SFX-WoW/Masque#377]
### Game Flavor

Retail

### Game Version

10.2.7

### Add-On Version

10.2.8

### Description

After the update glow effects in classic enhanced, modern enchanced and zoomed have changed. They became almost invisible.
Below are screenshots from zoomed before and after the update.
Can we get the old glow effect back or make a selectable setting?

### Screenshots

![image](https://github.com/user-attachments/assets/de46d4c7-c878-4435-9aaa-e1c1a3f46aad) - 5/7/2024 update
![image](https://github.com/user-attachments/assets/b352f48c-0da1-4e6c-9090-3dbea273d44c) - 7/11/2024 update

**Comment by StormFX** [comment]
This is intended and part of them being "Enhanced". That said, I'll be adding an option to toggle between the types of spell alerts, so in the next release, you'll be able to revert to the default alert style. In the interim, you should be able to disable the new style by commenting out the `Shape = "Shape",` line. Eg, for Zoomed, change line 32 from:

```lua
	Shape = "Square",
```
To:
```lua
	--Shape = "Square",
```

**Comment by StormFX** [comment]
Added an option to use **Blizzard**'s default spell alerts in **Options** > **General Settings** > **Advanced**.

**Comment by StormFX** [comment]
Did this fix your issue?

**Comment by artazika** [comment]
Yeah, thank you! Everything works as before
