### ISSUE TITLE
Plater + Masque Bug after Update

### ISSUE THREAD

**Issue by Jaidy88** [SFX-WoW/Masque#379]
### Game Flavor

Retail

### Game Version

10.2.7

### Add-On Version

10.2.8

### Description

so far the latest update works very well. the only problem i have is when my shadow word pain only lasts 3 seconds in plater the icon glows, as soon as the glow is activated masque does weird things - see screenshot

### Screenshots

![2728ad549b81f55e9c190a321f66ebf2 (1)](https://github.com/user-attachments/assets/12c15ddd-ce4c-4924-9eaf-c8d1fcb0868b)

**Comment by StormFX** [comment]
Masque wasn't really designed for nameplate buffs/debuffs and they certainly shouldn't have spell alerts on them. Spell alerts are exclusive to action buttons. Try disabling the start animation. Masque > Options > General > Advanced. Set it to "Loop Only".

**Comment by Jaidy88** [comment]
![a04d08aa647c1dcbae959fbb2c5a1510](https://github.com/user-attachments/assets/9e13911c-d18a-4204-8727-7a25b47b58a1)


this is my setting in advanced, should i set it to loop only?

**Comment by StormFX** [comment]
You have spell alerts disabled completely. Do they show on your action buttons?

**Comment by Jaidy88** [comment]
i didn't pay attention to that, since i am a healer ^^ i do everything via vuhdo or mouseover. in case of emergency i have to deactivate the plater script. would be a real pity, since i have been using the settings for 4 years as i set them back then

**Comment by StormFX** [comment]
Do you every have swirly effects appear on your action bars?

**Comment by StormFX** [comment]
I'll have to test it out, but it looks like whatever Plater Pandemic script you're using is bugging out. Do you know which one it is?

**Comment by Jaidy88** [comment]
no i don't see swirly effects on my action bars

yeah sure this is the script: https://wago.io/xOaQaujGr

**Comment by StormFX** [comment]
Try disabling the Plater group(s) in Masque's Skin Settings window for now.

**Comment by StormFX** [comment]
I just pushed a new release that adds an option under Masque Options > General Settings > Advanced to use the default Blizzard spell alerts. That should fix it.

**Comment by StormFX** [comment]
Let me know if this fixes it for you.

**Comment by Jaidy88** [comment]
sry i'll try to test it extensively again today, but it may not be until later in the evening. thanks for your effort

**Comment by StormFX** [comment]
Fixed in 3462145.
