### ISSUE TITLE
Bug: Blizzard Classic Cooldown Too Small

### ISSUE THREAD

**Issue by nullafy** [SFX-WoW/Masque#381]
### Game Flavor

Retail

### Game Version

10.2.7

### Add-On Version

10.2.10

### Description

I use the Blizzard_Classic skin (thank you for this!) with Bartender and since the latest updates the cooldown texture seems to just a few pixels too small. Picture attached. Oddly enough it's not for everything on cooldown as you can see.

Line 664/665 Width/Height is set to 32, setting this to 36 again fixed it.

Not a big deal and I know you said some skins may need to be fixed up, so just wanted to report this one.
Thanks!

### Steps to Reproduce

1. Bartender
2. Masque Blizzard Classic Skin

### Screenshots

![image](https://github.com/user-attachments/assets/0f3b0485-1f19-41e2-a921-abc7063e043a)

**Comment by StormFX** [comment]
I'll look into it. Thanks for the report.
