### ISSUE TITLE
Bug: Preventing other addons from grabbing minimap buttons

### ISSUE THREAD

**Issue by Smug-leaf** [SFX-WoW/Masque#387]
### Game Flavor

Retail

### Game Version

11.0.0

### Add-On Version

11.0.0

### Description

Masque is preventing movement of minimap buttons ever since the prepatch launch, causing them to stay locked in place. Possible conflict with specific add-ons that deal with minimaps/button placements (Hidingbar, Elvui, etc)

**Comment by Smug-leaf** [comment]
After further testing, it seems the issue is specifically caused from a conflict with Masque, Hidingbar, and buttons from the Total Roleplay 3 addon, so it isn't an issue caused by Masque specifically.

**Comment by StormFX** [comment]
Masque only interacts with buttons that are explicitly passed to it, so unless another add-on is doing that, it's unrelated to Masque.

**Comment by Smug-leaf** [comment]
It was specifically an issue with the way HidingBar is trying to grab buttons from other addons that aren't databroker based., and it was causing a conflict with masque's settings. I was able to resolve the issue by changing some settings of the addon in question, so you are correct, it's not a Masque issue.

**Comment by StormFX** [comment]
Glad you got it figured out! Closing this.
