### ISSUE TITLE
Bug: Skin not Reverting After Disable

### ISSUE THREAD

**Issue by Huf12** [SFX-WoW/Masque#390]
### Game Flavor

Retail

### Game Version

11.02

### Add-On Version

11.0.1 latest version on curseforge

### Description

Masque cant be turned off for weakauras. It reverts back to modern enhanced for me atleast. I tried this with only weakauras and masque turned on. The screenshot shows "new 2" icon which is the icon in the bottom right corner. Masque is disabled, it still hows modern enhanced. This is the same for any other skin too, atleast the default ones that come with your addon. This wasnt the case yesterday, 11.02 did some work. Hope that helps, cheers

### Steps to Reproduce

1. create a basic weakaura icon
2. select zoomed skin for this icon in masque options
3. click disable for this icon in masque options
4. it will revert back to modern enhanced

### Screenshots

https://ibb.co/X7dbqbC

**Comment by StormFX** [comment]
You'll need to `/reload` after disabling it.
