### ISSUE TITLE
Bug: Not all skins showing up

### ISSUE THREAD

**Issue by vojtasrb** [SFX-WoW/Masque#391]
### Game Flavor

Retail

### Game Version

11.0.2

### Add-On Version

11.0.1

### Description

Not all skins are showing up in the list.

F.e. I can't see Masque_Squat. 

### Steps to Reproduce

1. Install Masque_Squat and Masque Addon
2. Look at the settings, it's not there
3. Profit

**Comment by Thuuna** [comment]
I have the same issue.

**Comment by StormFX** [comment]
1. Make sure that you have out-of-date add-ons enabled.
2. If there's an error about `GetAddOnMetadata`, you will need to manually edit the file and add `C_AddOns.` to the beginning of every occurrence of `GetAddOnMetadata` so that it reads `C_AddOns.GetAddOnMetadata`.

**Comment by Thuuna** [comment]
Thanks for the reply.

1. is enabled
2. There is no error about GetAddOnMetadata

**Comment by StormFX** [comment]
You must have errors suppressed or something. I can confirm the skin does need to be edited.

Change line 8 of main.lua (in the Masque_Shadowlands folder)

From:

```lua
local VERSION = GetAddOnMetadata(ADDON, "Version")
```
To:

```lua
local VERSION = C_AddOns.GetAddOnMetadata(ADDON, "Version")
```

**Comment by Thuuna** [comment]
Worked perfctly.

Thank you for yout time and effort. @StormFX

**Comment by StormFX** [comment]
No problem!

**Comment by vojtasrb** [comment]
Squat still not working unfortunately

**Comment by StormFX** [comment]
Apologize for the premature close.

**Comment by vojtasrb** [comment]
> Apologize for the premature close. Was assuming it was fixed and got side-tracked by the additional poster. And for future reference, the original poster should be able to re-open an issue.
> 
> > After editing the file, Squat still not working unfortunately
> 
> Shadowlands's code is different, so you'll need to adjust it. Change "VERSION" to "Version" in the example above. Lua is case-sensitive.
> 
> ![image](https://private-user-images.githubusercontent.com/1234928/358228063-1450bf02-2f9e-4013-9d78-cd65ff819180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDU2MzMsIm5iZiI6MTcyMzc0NTMzMywicGF0aCI6Ii8xMjM0OTI4LzM1ODIyODA2My0xNDUwYmYwMi0yZjllLTQwMTMtOWQ3OC1jZDY1ZmY4MTkxODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTgwODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE3ZDA1YWM4N2VhNGM3NDFhNmJhMDdjNTAyNjNlYTJmZjY0YTFjMjhmNjc3YjM1YTMwNzQ2NDZmNjhiOWM1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bq5x6WBkYM9o3TLr-kCBgcUimstMp1OLSQ8fCqoqgos) ![image](https://private-user-images.githubusercontent.com/1234928/358227899-6db4061b-8fd8-4e0a-9ed0-f82873666dee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDU2MzMsIm5iZiI6MTcyMzc0NTMzMywicGF0aCI6Ii8xMjM0OTI4LzM1ODIyNzg5OS02ZGI0MDYxYi04ZmQ4LTRlMGEtOWVkMC1mODI4NzM2NjZkZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTgwODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI3YmY4MTIzNGY5ZDNjZTZjMTg5ODA2YmU0OTBkZDFkNjg1MTgzMGQ0YjNiODliMmFiNzllMzExMDE5ZWMxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EPqjHQIYFrBzj5Dz5Cqj-rtrACXgoCcQWGE6Hqm-W1Y) ![image](https://private-user-images.githubusercontent.com/1234928/358228363-6e638534-c9e3-4409-8019-a8b4444d1e36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDU2MzMsIm5iZiI6MTcyMzc0NTMzMywicGF0aCI6Ii8xMjM0OTI4LzM1ODIyODM2My02ZTYzODUzNC1jOWUzLTQ0MDktODAxOS1hOGI0NDQ0ZDFlMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTgwODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNjMTU2YzkwNzlmN2E5N2QzY2YwNWY0ZDVhZjk1OWMwZWUyN2VlODZkY2I5ZThkMTc1MzczYjIyZGNhNjg0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YjrvLBwZ5zSyNcsPf7LMLcGvZQvpQh3AIhyS_JgwPF8)

Hey dude, it works now. Thanks!

**Comment by StormFX** [comment]
Good to hear!
