### ISSUE TITLE
Bug: Skins Not Loading

### ISSUE THREAD

**Issue by vojtasrb** [SFX-WoW/Masque#392]
### Game Flavor

Retail

### Game Version

11.0.2

### Add-On Version

11.0.1

### Description

Some skins not working. Masque_Squat f.e.

### Steps to Reproduce

1. Download Masque_Squat and Masque
2. Install to Addons
3. Won't show up in the list

**Comment by zeritox07** [comment]
i got the same issue, redownloaded masque and their skins with all of them loaded but still won't show up on my skins list nor they work.

**Comment by StormFX** [comment]
https://github.com/SFX-WoW/Masque/issues/391

**Comment by vojtasrb** [comment]
> The solution can be found here: #391
> 
> Alternatively, add the following to the top of skin's `.lua` file:
> 
> ```lua
> local GetAddOnMetadata = C_AddOns.GetAddOnMetadata
> ```

I tried this with Masque_Squat. It doesn't work.
