### ISSUE TITLE
Swap SpellAlert manually

### ISSUE THREAD

**Issue by jamesmckeever** [SFX-WoW/Masque#394]
### Game Flavor

Retail

### Game Version

11.02

### Add-On Version

11.01

### Describe the Improvement

Hi,

I love using the classic style of bars, but with the modern spell alert. I swapped this manually myself by changing Core/Regions/SpellAlert FlipBooks table, but this is a pain to do with every future update. Would be cool to be able to modify this in the addon itself.

**Comment by StormFX** [comment]
> In case you missed it, you can now select the style of spell alerts that Masque uses and which animations are shown in the Retail client. These options are found under Masque > General Settings > Advanced.

**Comment by jamesmckeever** [comment]
My mistake, thank  you!
