### ISSUE TITLE
Bug: Animations Settings not Applying Correctly

### ISSUE THREAD

**Issue by zhpzhp** [SFX-WoW/Masque#396]
### Game Flavor

Retail

### Game Version

11.0.2

### Add-On Version

11.0.1

### Description

Disable the three options(cast animation, interrupt animation, targeting reticles) in the advanced tab only works until the reload.

### Screenshots

![1](https://github.com/user-attachments/assets/ccbd1402-58d4-45b6-90ea-857610519a58)

**Comment by StormFX** [comment]
I have confirmed this to be a bug. For some reason, the events for this are being registered after the `PLAYER_LOGIN` event. The following should help until I get a release put out. Add this at line 55 of `Masque.lua`.

```lua
-- Events Frame
if WOW_RETAIL then
	local MSQ_EVENTS_FRAME = CreateFrame("Frame")
	MSQ_EVENTS_FRAME:Hide()

	local function OnEvent(...)
		print("Hello")
		local db = Core.db.profile
		local UpdateEffect = Core.UpdateEffect

		for k, v in pairs(db.Effects) do
			UpdateEffect(k, v)
		end	
	end

	-- Delay the unregistering of events until after `PLAYER_LOGIN`.
	MSQ_EVENTS_FRAME:RegisterEvent("PLAYER_ENTERING_WORLD")
	MSQ_EVENTS_FRAME:SetScript("OnEvent", OnEvent)
end
```

**Comment by zhpzhp** [comment]
Works perfectly! Thank you

**Comment by StormFX** [comment]
You bet. I'll try to get a release sometime this week or next. Busy schedule.
