### ISSUE TITLE
Bug: Category Editing Occasionally Fails

### ISSUE THREAD

**Issue by Elitesparkle** [SFX-WoW/Masque#397]
### Game Flavor

Retail

### Game Version

11.0.2

### Add-On Version

11.0.1

### Description

Masque can occasionally fail to change settings to some elements that are in the selected category when changing settings.

### Steps to Reproduce

I don't know a way to consistently reproduce this issue.

The following steps can be used to see it again when it happens:

1. open Masque's options;
2. go in Skin Settings;
3. select a category (eg. WeakAuras);
4. change something (eg. Skin, Colors).

### Error Message

```text
No errors. I have BugSack and BugGrabber installed.
```

### Notes

I'm pretty sure it only happens with WeakAuras.

**Comment by StormFX** [comment]
Generally, issues with WeakAuras are related to how the buttons are generated. The only way to really address those types of issues is to purge the skin settings for WeakAuras. Disable WA > Reload > Masque / Options / General / Developer / Clean Database > Enable WA > Reload. Other than that, there's no way for me to know what's going on with being able to reproduce it.
