### ISSUE TITLE
Feature: always remember the scaling setting so it doesn't reset if you temporarily disable it

### ISSUE THREAD

**Issue by zeenk** [SFX-WoW/Masque#403]
### Game Flavor

Retail

### Game Version

11.0.5

### Add-On Version

11.0.2

### Describe the Improvement

If you temporarily disable the scale setting in Masque it always resets to 1, would be nice so that it remembers the setting you manually changed it to so you don't have to change it back everytime if you at some point disable it

### Screenshots

https://github.com/user-attachments/assets/32614928-7e9f-495e-b925-58386a3c5d83

**Comment by StormFX** [comment]
The default is 1.0. If you disable it, it reverts to the default. I'm not seeing the problem.

**Comment by zeenk** [comment]
It's not really a "problem" more of a QoL thing, so you don't have to change it back to your desired value next time if you would temporarily turn it off. 
But it's not that big of a deal so I'm just gonna close this one.
