### ISSUE TITLE
Masque Sometimes not Applying to WeakAuras

### ISSUE THREAD

**Issue by Montrazul** [SFX-WoW/Masque#45]
I installed Masque today to use it on `WeakAuras`. I applied `Clean Icons - Square` to my `WeakAuras`.
As you can see on the following picture it is working most of the time. But sometimes when new Auras (in this case - Buffs) appear masque is not applied to them. You can see that on the 14 seconds blue buff on the image.

![auras](https://user-images.githubusercontent.com/13464567/51344147-44046280-1a98-11e9-9ba4-8ef44c3d45f7.png)

**Comment by StormFX** [comment]
This is something Weak Auras will have to address, as Masque doesn't monitor changes, etc.

**Comment by Montrazul** [comment]
Ok. I reported the issue here: https://github.com/WeakAuras/WeakAuras2/issues/1111

**Comment by StormFX** [comment]
Ref: bb27b75
