### ISSUE TITLE
Feature Request: Classic Support

### ISSUE THREAD

**Issue by ManneN1** [SFX-WoW/Masque#65]
Hello,

Will Masque be updated for Classic WoW (1.13)? If so, is there an ETA?

Best Regards,
ManneN

**Comment by StormFX** [comment]
I won't know until it's released.

**Comment by ManneN1** [comment]
Until Classic WoW is released? 

If it's of any help the final stress test is live and available to everyone with an active subscription.

**Comment by StormFX** [comment]
I only test/update on live servers.

**Comment by qhilmv** [comment]
I tried the latest stable version (v8.0.1) and it seems to be working without any problem.

**Comment by StormFX** [comment]
I appreciate it. I'll need to test the latest version due to some additional API that was added. Hopefully, I'll be able to disable some features with a simple version check, if necessary. I really can't be bothered with maintaining two separate versions.

**Comment by ManneN1** [comment]
Sure, it works by itself. It does however not work together with Bartender (updated for Classic). I got it working with Dominos, but with a whole bunch of errors.

Good luck on updating/maintaining the addon.

**Comment by qhilmv** [comment]
Well, I'm using (or I used) Masque with Bartender and got no errors.
Maybe you used a wrong/incompatible version of Bartender4. Mine is "v4.8.3-19-classic" (alpha build) and it's not even the newest one.

**Comment by StormFX** [comment]
It looks like most of the API that Masque uses is intact, so I've made a few minor tweaks and released a beta for Classic.

**Comment by qhilmv** [comment]
Hey StormFX,
I tested your Classic version of Masque yesterday but it didn't work. No option entry, no chat commands, nothing. I reinstalled the older version (retail) to make it work again.

**Comment by qhilmv** [comment]
Well, I'll try it again later. I guess, I know what the problem was.

**Comment by StormFX** [comment]
Since this is already implemented, I'm closing this.
